### ISSUE TITLE
How to properly use this with scoped views?

### ISSUE THREAD

**Issue by K1N5L4Y3R** [tigrish/devise-i18n#220]
## Rationale
I used `rails g devise:i18n:views user` to create scoped views for my `User` model, since I will have multiple Devise models (see [Devise documentation](https://github.com/plataformatec/devise#configuring-views)). This did create the views in `app/views/users` as expected.
I also used `rails g devise:i18n:locale es-MX` to generate the locale file, and it was generated as expected.

## Problem
Since the views are scoped,  I had to do the following:
```
# devise.views.es-MX.yml
devise: &devise_views
  confirmations:
  # ....
users:
    <<: *devise_views
```
in order for the app to properly find the translations.

I can also see errors like `translation missing: es-MX.devise.failure.user.not_found_in_database` , which, again, could be solved with the following:
```
# devise.views.es-MX.yml
failure:
      user: &failure_user
        already_authenticated: Ya has iniciado sesión.
        # ...
      <<: *failure_user
```

## Question
Is there an "official" way to accomplish what I need (i.e. generating locale files that work for scoped views), or can I get a full list of where in the locale file do I need to patch as previously mentioned?
