### ISSUE TITLE
[DEVISE] devise.registrations.inactive_signed_up in yml files is deprecated

### ISSUE THREAD

**Issue by hron84** [tigrish/devise-i18n#3]
Devise complaining about some deprecated locale entries

```
[DEVISE] devise.registrations.inactive_signed_up in yml files is deprecated, please use devise.registrations.signed_up_but_REASON instead. The default values are:

en:
  devise:
    registrations:
      signed_up_but_unconfirmed: 'A message with a confirmation link has been sent to your email address. Please open the link to activate your account.'
      signed_up_but_inactive: 'You have signed up successfully. However, we could not sign you in because your account is not yet activated.'
      signed_up_but_locked: 'You have signed up successfully. However, we could not sign you in because your account is locked.'
```

I currently have a branch for fix complaining in hungarian translation, but it would be great if it is merged into other languages. However, you do not mention them in the gem, and I do not know how I can notify them about this change.
