### ISSUE TITLE
English pluralization of `not_saved` is not consistent with other languages

### ISSUE THREAD

**Issue by tonekk** [tigrish/devise-i18n#342]
Current `en.yml`:
```yaml
      not_saved:
        one: '1 error prohibited this %{resource} from being saved:'
        other: "%{count} errors prohibited this %{resource} from being saved:"
```

More consistent with e.g. `de.yml` would be something like:
```yaml
      not_saved:
        one:  '%{resource} could not be saved due to the following error:'
        other: '%{count} errors prohibited this %{resource} from being saved:'
```
