### ISSUE TITLE
View localisation?

### ISSUE THREAD

**Issue by maxcal** [tigrish/devise-i18n#92]
Are view localisation keys out of scope for this project? 

example:

``` YAML
registrations:
      edit:
        edit: "Edit"
        email: "Email"
        password: "Password"
        password_confirmation: "Password confirmation"
        current_password: "Current password"
        cancel_my_account: "Cancel my account"
        update: "Update"
        back: "Back"
        are_you_sure: "Are you sure?"
        unhappy: "Unhappy?"
        we_need_password_to_confirm: "(we need your current password to confirm your changes)"
        leave_blank_if_no_change: "(leave blank if you don't want to change it)"
      new:
        sign_up: "Sign up"
        email: "Email"
        password: 'Password'
        password_confirmation: "Password confirmation"
```
